# Generated by Django 3.0.1 on 2019-12-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20191230_0244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tidisplay',
            table='ti_display',
        ),
    ]
