# Generated by Django 3.0.1 on 2019-12-30 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_auto_20191230_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiKeyboard',
            fields=[
                ('idkeyboard', models.AutoField(primary_key=True, serialize=False)),
                ('id_kb_trademark', models.IntegerField()),
                ('kb_reference', models.CharField(max_length=50)),
                ('kb_serial', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ti_keyboard',
            },
        ),
        migrations.CreateModel(
            name='TiMouse',
            fields=[
                ('idmouse', models.AutoField(primary_key=True, serialize=False)),
                ('id_mouse_trademark', models.IntegerField()),
                ('mouse_reference', models.CharField(max_length=50)),
                ('mouse_serial', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ti_mouse',
            },
        ),
        migrations.CreateModel(
            name='TiOffice',
            fields=[
                ('idti_office', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=50)),
                ('office_version', models.FloatField()),
                ('office_reference', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ti_office',
            },
        ),
        migrations.CreateModel(
            name='TiOperatingSystem',
            fields=[
                ('idti_operating_system', models.AutoField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.FloatField()),
                ('os_reference', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ti_operating_system',
            },
        ),
        migrations.CreateModel(
            name='TiPosition',
            fields=[
                ('idti_position', models.AutoField(primary_key=True, serialize=False)),
                ('position_description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ti_position',
            },
        ),
        migrations.CreateModel(
            name='TiTower',
            fields=[
                ('idti_tower', models.AutoField(primary_key=True, serialize=False)),
                ('tower_description', models.TextField()),
                ('tower_reference', models.CharField(max_length=50)),
                ('tower_serial', models.CharField(max_length=50)),
                ('id_type', models.IntegerField()),
                ('id_tower_trademark', models.IntegerField()),
                ('id_processor', models.IntegerField()),
                ('id_hard_disk', models.IntegerField()),
                ('id_ram', models.IntegerField(db_column='id_RAM')),
                ('id_cd_player', models.IntegerField(db_column='id_CD_player')),
                ('id_changer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ti_tower',
            },
        ),
        migrations.CreateModel(
            name='TiResponsible',
            fields=[
                ('idti_responsible', models.AutoField(primary_key=True, serialize=False)),
                ('rp_name', models.CharField(max_length=50)),
                ('rp_dni', models.BigIntegerField()),
                ('id_position', models.ForeignKey(db_column='id_position', on_delete=django.db.models.deletion.DO_NOTHING, to='computer.TiPosition')),
            ],
            options={
                'db_table': 'ti_responsible',
            },
        ),
    ]
